json.id inside_product.id
json.name inside_product.name
json.price inside_product.price
json.description inside_product.description
json.image_url inside_product.images
json.tax inside_product.tax
json.discounted inside_product.is_discounted?
json.total inside_product.total
json.supplier inside_product.supplier
#json.supplier_name inside_product.supplier
#json.images inside_product.images
json.user current_user
json.categories inside_product.categories
